#ifndef PLUGIN_PLUGIN_GLOBAL_H
#define PLUGIN_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGIN_PLUGIN_LIBRARY)
#  define PLUGIN_PLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_PLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGIN_PLUGIN_GLOBAL_H
